name: 'ecommerce_dbt'
version: '1.0.0'
config-version: 2

profile: 'analytics_warehouse_bq'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dbt:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    mart:
      +schema: mart
      +materialized: table

seeds:
  ecommerce_dbt:
    raw:
      +schema: raw