name: dbt CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-bigquery==1.7.0

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << 'EOF'
          analytics_warehouse_bq:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account-json
                project: analytics-warehouse-dev-major
                dataset: dbt_ci
                keyfile_json: "{{ env_var('GCP_KEYFILE_JSON') }}"
                threads: 4
                timeout_seconds: 300
                location: US
          EOF

      - name: Load seed data
        env:
          GCP_KEYFILE_JSON: ${{ secrets.GCP_CREDENTIALS }}
        run: dbt seed --target ci

      - name: Run dbt models (exclude elementary)
        env:
          GCP_KEYFILE_JSON: ${{ secrets.GCP_CREDENTIALS }}
        run: dbt run --target ci --exclude elementary --select "staging intermediate mart semantic"

      - name: Run dbt tests (exclude elementary)
        env:
          GCP_KEYFILE_JSON: ${{ secrets.GCP_CREDENTIALS }}
        run: dbt test --target ci --exclude elementary --select "staging intermediate mart"